import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show compute, listEquals;
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:ui';
import 'dart:math' as math;

import 'package:flutter/services.dart';
import 'package:file_picker/file_picker.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'features/reader/reader_pagination.dart';
import 'core/services/source_file_service.dart';
import 'features/billing/billing_monitor_page.dart';
import 'features/billing/billing_credentials_page.dart';
part 'core/theme.dart';
part 'core/persistence.dart';
part 'core/services/ai_service.dart';
part 'features/shelf/shelf.dart';
part 'features/works/book_detail.dart';
part 'features/works/book_characters_section.dart';
part 'features/works/book_source_file.dart';
part 'features/search/search.dart';
part 'features/reader/reader.dart';
part 'features/characters/character_card.dart';
part 'features/characters/character_detail_page.dart';
part 'features/characters/character_editor.dart';
part 'features/characters/character_card_page.dart';
part 'features/characters/character_model.dart';
part 'features/characters/add_character_dialog.dart';
part 'features/reader/reader_models.dart';
part 'features/reader/reader_image_store.dart';
part 'features/reader/reader_image_actions.dart';
part 'features/reader/reader_bookmarks.dart';
part 'features/reader/reader_navigation.dart';
part 'features/reader/reader_layout.dart';
part 'features/ai/ai_image_page.dart';
part 'shared/reader_widgets.dart';
part 'features/characters/character_pages.dart';
part 'features/characters/character_store.dart';
part 'features/characters/relations.dart';
part 'features/characters/relation_layout_service.dart';
part 'features/characters/relation_store.dart';
part 'features/characters/relation_form.dart';
part 'features/characters/character_ai.dart';
part 'core/models/work_models.dart';
part 'core/imported_work_store.dart';
part 'features/reader/reader_loading.dart';
part 'features/works/works.dart';
part 'features/ai/ai_gallery.dart';
part 'features/ai/ai_generate.dart';
part 'features/gallery/gallery.dart';
part 'features/worlds/worlds.dart';
part 'features/settings/mine_page.dart';
part 'features/settings/error_log_page.dart';
part 'features/settings/api_cost_monitor.dart';
part 'features/settings/local_api_cost_estimate.dart';
part 'features/settings/reading_preferences.dart';
part 'features/settings/ai_service_config.dart';
part 'features/settings/api_request_logs_card.dart';
part 'features/settings/ai_connection_test.dart';
part 'features/settings/data_management.dart';
part 'app/app_shell.dart';

final ValueNotifier<bool> appDarkMode = ValueNotifier<bool>(false);
