import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:ui';

import 'package:flutter/services.dart';
import 'package:file_picker/file_picker.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
part 'core/theme.dart';
part 'core/persistence.dart';
part 'core/services/ai_service.dart';
part 'features/shelf/shelf.dart';
part 'features/works/book_detail.dart';
part 'features/search/search.dart';
part 'features/reader/reader.dart';
part 'features/ai/ai_image_page.dart';
part 'shared/reader_widgets.dart';
part 'features/characters/character_pages.dart';
part 'features/characters/relations.dart';
part 'features/characters/character_ai.dart';
part 'core/models/work_models.dart';
part 'features/works/works.dart';
part 'features/ai/ai_gallery.dart';
part 'features/ai/ai_generate.dart';
part 'features/gallery/gallery.dart';
part 'features/worlds/worlds.dart';
part 'features/settings/mine_page.dart';
part 'features/settings/error_log_page.dart';
part 'features/settings/api_cost_monitor.dart';
part 'features/settings/reading_preferences.dart';
part 'features/settings/ai_service_config.dart';
part 'features/settings/data_management.dart';
part 'app/app_shell.dart';

final ValueNotifier<bool> appDarkMode = ValueNotifier<bool>(false);
